name: jizhang
description: 极简记账 - 个人离线记账 App
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  speech_to_text: ^6.6.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
